#!/bin/sh

CLASSPATH=${CLASSPATH}:${GRIDSWEEPER_ROOT}/classes/GridSweeper.jar
CLASS="edu.umich.lsa.cscs.gridsweeper.GridSweeper"
ADAPTER="edu.umich.lsa.cscs.gridsweeper.DroneAdapter"
java ${CLASS} -a ${ADAPTER} $@
