#!/bin/sh

CLASSPATH=${CLASSPATH}:${GRIDSWEEPER_ROOT}/classes/GridSweeper.jar
CLASS="com.edbaskerville.gridsweeper.GridSweeper"
ADAPTER="com.edbaskerville.gridsweeper.DroneAdapter"
java ${CLASS} -a ${ADAPTER} $@
