#!/bin/sh

# Configuration information for debugging
echo "gsrunner starting..." 1>&2
echo "hostname: `hostname`" 1>&2
java -version 1>&2
echo "GRIDSWEEPER_ROOT: $GRIDSWEEPER_ROOT" 1>&2
CLASSPATH=${CLASSPATH}:${GRIDSWEEPER_ROOT}/classes/GridSweeper.jar
echo "CLASSPATH: $CLASSPATH" 1>&2
CLASS=edu.umich.lsa.cscs.gridsweeper.GridSweeperRunner
java ${CLASS} "$@"
